os:
  - linux
  - osx
  - windows
  
language: node_js

branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+.*/

env:
  - TEST_COMMAND=test

script: "npm run lint && npm run $TEST_COMMAND"

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Run the deployment after all jobs have been successfully completed.
# https://docs.travis-ci.com/user/build-stages
jobs:
  include:
    - stage: deploy
      env: TEST_COMMAND=none
      script: bash <(curl -s https://blackbaud.github.io/skyux-travis/after-success.sh)
