branches:
  only:
    - master

environment:
  nodejs_version: "10"

install:
  - choco install googlechrome --ignore-checksums
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - nyc jasmine --config=jasmine.json

# Don't actually build.
build: off